services:
  db:
    image: postgres:15
    container_name: postgres_dars
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: dars3
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build: .
    container_name: nest_dars
    restart: always
    env_file:
      - .env
    ports:
      - "9090:3000"
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run start:prod
      "

volumes:
  postgres: